######################################################################
# Automatically generated by qmake (2.01a) Thu May 21 15:14:20 2020
######################################################################

CC=gcc
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += loopint.c
